require('cfg.mini.icons')
require('cfg.mini.move')
require('cfg.mini.statusline')
require('cfg.mini.trailspace')
require('cfg.mini.pairs')
require('cfg.mini.comment')
require('cfg.mini.hipatterns')
require('cfg.mini.surround')
